### ISSUE TITLE
Documentation does not match actual behavior for JsonPath

### ISSUE THREAD

**Issue by howardjohn** [awslabs/states-language#10]
Under [Input and Output Processing](https://states-language.net/spec.html#filters), the spec states that:

> Note that JsonPath can yield multiple values when applied to an input JSON text. For example, given the text:
> 
> `{ "a": [1, 2, 3, 4] }`
> Then if the JsonPath `$.a[0..1]` is appplied, the result will be two JSON texts, 1 and 2. When this happens, to produce the effective input, the interpreter gathers the texts into an array, so in this example the state would see the input:
> 
> `[ 1, 2 ]`

This does not seem to be correct. If you run this in https://jsonpath.herokuapp.com/, it gives a syntax error. Running this example in Step Functions gives a result of just `1` rather than `[1, 2]`. 

It looks like `"InputPath": "$.a[0,1]"` works and gives `[1, 2]` as the output, so I would guess the documentation is just wrong there.

**Comment by timbray** [comment]
Almost. You're correct, the spec is wrong.  The range operator is ":" not ".." and the second number is a higher-than bound.  So if you want the first two numbers you have to say "$.a[0:2]"'; I've checked, this works as expected.

The "," operator works, but just selects items.  So while [0,1] gives [1,2] in your example, [0,2] would give [1,3].

Anyhow, thanks for raising this and I'll fix this in the next revision of the spec.

**Comment by timbray** [comment]
Fixed, I think.
