### ISSUE TITLE
Clarification requested: When does States.ParameterPathFailure occur?

### ISSUE THREAD

**Issue by jezhiggins** [awslabs/states-language#12]
The section on the parameters fields includes the sentence 

> If the path is legal but cannot be applied successfully the Interpreter fails the machine execution with an Error Name of “States.ParameterPathFailure”.

It's not clear to me in what circumstances this error might occur.  Does it simply mean that a path fails to match any node in the input?
___

In the example, a Parameters field of 

```
"Parameters": {
    "flagged": true,
    "parts": {
      "first.$": "$.vals[0]",
      "last3.$": "$.vals[3:]"
    }
 }
```

and an input of 
```
{
  "flagged": 7,
  "vals": [0, 10, 20, 30, 40, 50]
}
```
gives an effective input of 
```
{
  "flagged": true,
  "parts": {
    "first": 0,
    "last3": [30, 40, 50]
  }
}
```

If the input was instead 
```
{ 
  "flagged": true,
  "vals": 0
}
```
then the paths `$.vals[0]` and `$.vals[3:]` both fail to match.  

Would something like this trigger the error?

Thanks.

**Comment by timbray** [comment]
Terribly sorry I missed this comment somehow.  Yes, I believe your reading is correct, and both those paths would raise the error if you had "vals": 0 (or no vals at all).  Could the spec language be improved here?

**Comment by jezhiggins** [comment]
That's quite alright - no need to apologise at all.

I think the language in the spec is fine - we agree here, after all. I do wonder if a few (non-normative) examples might help though. There are clarifying examples in the text for the interaction of InputPath & Parameters and for ResultPath & OutputPath which are very helpful. An example for each of the error states would be useful, although I'm aware my perspective as an implementer rather than a user is unusual :)
