### ISSUE TITLE
"Not" choice rule description in spec appears to be out of date

### ISSUE THREAD

**Issue by mattsb42-aws** [awslabs/states-language#15]
According to the spec, the `Not` choice rule has the following restrictions:

> The value of a “Not” operator MUST be a single Choice Rule, that MUST NOT contain “Next” fields; the “Next” field can only appear in a top-level Choice Rule.

However, according to the developer guide:

> You can create complex, nested Choice Rules using And, Not, and Or. However, the Next field can appear only in a top-level Choice Rule. 

In testing, it appears that the developer guide is correct.

I'm not sure if this is unclear wording or if the functionality has actually changed.
I would read `The value of a “Not” operator MUST be a single Choice Rule` as meaning that a `Not` operator MUST NOT contain an `And` or `Or` operator, which does not appear to be the case.

**Comment by wong-a** [comment]
I'm resolving this because I think the latest version of the spec already clarifies the concern mentioned here. See conversation on the PR: https://github.com/awslabs/states-language/pull/16#discussion_r494008932

Please re-open if not the case.
