### ISSUE TITLE
Create an object key from a variable

### ISSUE THREAD

**Issue by slootjes** [awslabs/states-language#32]
It currently does not seem possible to create a key from a variable. For instance, I tried to create input for a DynamoDB Batch Write which requires the name of the table to be the key of the object.

```
{
  "RequestItems": {
    "$.BatchInput.table.$": "$.Items"
  }
}
```

What I would like to have as result is this:
```
{
  "RequestItems": {
    "name-of-my-table": [
      {
        "PutRequest": {
          "Item": {
            "pk": {
              "S": "some-value"
            },
```

however it currently resolves to this:
```
{
  "RequestItems": {
    "$.BatchInput.table": [
      {
        "PutRequest": {
          "Item": {
            "pk": {
              "S": "some-value"
            },
```

Maybe a new syntax could be implemented like 
```
{
  "RequestItems": {
    "{$.BatchInput.table}.$": "$.Items"
  }
}
```
so the parser understands that it needs to resolve the name of the key.

**Comment by yaythomas** [comment]
thanks for the suggestion, @slootjes, much appreciated!

yes, you're correct, the dynamic path evaluation does not apply to keys, only to values.

to work around this, you could use an [Intrinsic Functions like StringToJson](https://docs.aws.amazon.com/step-functions/latest/dg/intrinsic-functions.html#asl-intrsc-func-json-manipulate) to prepare your payload in a Pass state. 

```
 "MyData.$": "States.StringToJson(States.Format('\\{\"{}\":\"{}\"\\}', $.A, $.B))"
```

I appreciate that this is not necessarily the most straightforward approach, though! It might even be the case that using a transformer Lambda function to prepare the payload is more convenient.

We are actively working to improve Step Functions to make this sort of thing easier!

**Comment by timbray** [comment]
It's a long-standing and well-known shortcoming of JSONPath that it offers no good way to get at the *names* of object members. Glad the team is looking at this, it's a hard problem.

**Comment by slootjes** [comment]
While I appreciate the effort, as far as I can see the provided solution won't really work without also making all other json inputs a string as the StringToJson requires a string, not an object according to the documentation. This won't make the state machine definition readable. A transfer Lambda obviously is a solution for everything but requiring a Lambda for such a simple transformation doesn't make sense to me in a service like StepFunctions. 

This should not be closed as the issue is not solved, only a workaround is provided.
