### ISSUE TITLE
Wanted: A StringPrefix comparison operator in Choice state

### ISSUE THREAD

**Issue by timbray** [awslabs/states-language#8]
I'd like to be able to write

{ "StringPrefix": "volume-", "Next": "volumizer", "Variable": "…" }

**Comment by timbray** [comment]
Sounds like a good idea.  Other sensible proposals for additions:
- test for absence/presence of a field
- test for null value of a field (as in JSON null, not absence)

**Comment by vdaron** [comment]
Both these features are now part of the specification

**Comment by wong-a** [comment]
Implemented by the `StringMatches` operator merged in https://github.com/awslabs/states-language/pull/18
